version: "2"

services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    networks:
      - hello-world
  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes
    networks:
      - hello-world
    volumes:
      - redis-data:/data

networks:
  hello-world:
    driver: bridge

volumes:
  redis-data:
    driver: local
