version: "2"

services:
  web:
    image: ${DTR_URL}/admin/hello-world-python:${GITID}
    ports:
     - "5000"
    networks:
      - hello-world
  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes
    networks:
      - hello-world
    volumes:
      - redis-data:/data

networks:
  hello-world:
    driver: overlay

volumes:
  redis-data:
    driver: local
